export const ZONE_MAP: Record<string, string> = {
  "gachibowli": "West",
  "kondapur": "West",
  "madhapur": "West",
  "hitech-city": "West",
  "manikonda": "West",
  "nallagandla": "West",
  "kukatpally": "West",
  "hafeezpet": "West",
  "miyapur": "West",
  "tellapur": "West",
  "kokapet": "West",
  "narsingi": "South",
  "chandanagar": "West",
  "bachupally": "North",
  "kompally": "North",
  "nizampet": "North",
  "kphb-colony": "West",
  "jubilee-hills": "Central",
  "banjara-hills": "Central",
  "srinagar-colony": "Central",
  "film-nagar": "Central",
  "panjagutta": "Central",
  "ameerpet": "Central",
  "begumpet": "Central",
  "secunderabad": "East",
  "malkajgiri": "East",
  "uppal": "East",
  "dilsukhnagar": "South",
  "malakpet": "South",
  "nampally": "Central",
  "himayath-nagar": "Central",
  "lb-nagar": "East",
  "mehdipatnam": "South",
  "attapur": "South",
};

export function getZone(slug: string): string {
  return ZONE_MAP[slug] ?? "Other";
}
